integrations:
  gcl:
    type: dataset
    ref: paperspace/ds7me5hgjbfht6q:8ngwr2a
  ogbn_arxiv:
    type: dataset
    ref: paperspace/dse7nwrf3tr7cl8:a27q61l
  ogb_lsc_pcqm4mv2:
    type: dataset
    ref: paperspace/dsny3t160bciwgy:yzzo2ta
  poplar-executables-tf2-3-2:
    type: dataset
    ref: paperspace/ds2ien2b5pkqvcm:2zfgw9w
